mail:
  fromMail:
    addr: 2580012389@qq.com
  captchaMail:
    subject: 【网络教学系统-Alpha】
    template: 验证码 {0} (${captcha.mail.expireTimeout}分钟内有效)。如非本人操作，请忽略本短信。
captcha:
  SMS:
    expireTimeout: 10
    timeUnit: MINUTES
  web:
    expireTimeout: 15
    timeUnit: MINUTES
  mail:
    expireTimeout: 10
    timeUnit: MINUTES
SMS:
  module: 【网络教学系统-Alpha】验证码 {0} (${captcha.SMS.expireTimeout}分钟内有效)。如非本人操作，请忽略本短信。
  request:
    sysMethod: POST
    sysDomain: dysmsapi.aliyuncs.com
    sysVersion: 2017-05-25
    sysAction: SendSms
    queryParameter:
      regionId: cn-hangzhou
      signName: 网络教学系统Unit
      templateCode: SMS_190784667
fileplan:
  basePath: E:\classpie\fileplan
  chunkThreshold: 30
  tempPath: E:\classpie\tempDirectory
notice:
  release-task:
    subject: 发布新作业
    content: "[课程{0}] 老师 {1} 发布了新作业,作业标题为[ {2} ],请及时查看完成"
  recall-task:
    subject: 作业打回
    content: "[课程{0}] 老师 {1} 打回了你提交的关于[ {2} ]的作业,请重新提交"
  correct-task:
    subject: 作业已批阅
    content: "[课程{0}] 老师 {1} 批阅了你提交的关于[ {2} ]的作业,请查看成绩"
  expedite-task:
    subject: 作业催交
    content: "[课程{0}] 老师 {1} 催交作业[ {2} ]"
cache:
  pdf-file:
    name: pdfFile
    expire-timeout: 10
    time-unit: MINUTES
