spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    username: root
    url: jdbc:mysql://localhost:3306/classroom_pie?uesSSL=false&serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8
    password: 991103goodluck
    druid:
      filters: stat,wall,slf4j
      initial-size: 5
      min-idle: 5
      max-active: 20
      max-wait: 60000
      test-while-idle: true
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 30000
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      stat-view-servlet:
        login-username: admin
        login-password: 123456
        enabled: true
      web-stat-filter:
        profile-enable: true
        enabled: true
        session-stat-max-count: 2000
        principal-session-name: session_user_key
        url-pattern: "/*"
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,*.jsp,/druid/*"
      reset-stat-enable: true
    driver-class-name: com.mysql.cj.jdbc.Driver

