spring:
  session:
    store-type: redis
    redis:
      flush-mode: on_save
      namespace: spring.seesion
  mail:
    host: smtp.qq.com
    username: 2580012389@qq.com
    password: drhvlyowndjsdjfd
    default-encoding: UTF-8
    port: 465
    protocol: smtps
    test-connection: true
  data:
    redis:
      repositories:
        enabled: true
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    jedis:
      pool:
        max-active: 100
        max-idle: 10
        max-wait: 100000
    timeout: 5000
    password: 991103goodluck
